// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function actionsBuilder(dispatch) {
  return {
          add: (function (param) {
              return Curry._1(dispatch, /* Add */0);
            }),
          remove: (function (param) {
              return Curry._1(dispatch, /* Remove */1);
            }),
          set: (function (value) {
              return Curry._1(dispatch, /* Set */{
                          _0: value
                        });
            })
        };
}

function update(state, action) {
  if (typeof action === "number") {
    if (action !== 0) {
      return state - 1 | 0;
    } else {
      return state + 1 | 0;
    }
  } else {
    return action._0;
  }
}

function view(model, props, actions) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Value: " + String(model)), React.createElement("button", {
                  onClick: actions.add
                }, "Add"), React.createElement("button", {
                  onClick: actions.remove
                }, "Remove"));
}

function useEffects(model, props, actions) {
  React.useEffect((function () {
          setTimeout((function (param) {
                  return Curry._1(actions.set, 30);
                }), 2000);
          
        }), []);
  React.useEffect((function () {
          if (model === 10 || model === -10) {
            Curry._1(actions.set, 0);
          }
          
        }), [model]);
  
}

function make(props) {
  var match = React.useReducer(update, 0);
  var dispatch = match[1];
  var model = match[0];
  var actions = React.useMemo((function () {
          return actionsBuilder(dispatch);
        }), []);
  useEffects(model, props, actions);
  return view(model, props, actions);
}

export {
  actionsBuilder ,
  update ,
  view ,
  useEffects ,
  make ,
  
}
/* react Not a pure module */
