// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function useSandbox(sandbox) {
  var match = React.useReducer((function (param, param$1) {
          return Curry._2(sandbox.update, param, param$1);
        }), sandbox.initialModel);
  return Curry._2(sandbox.view, match[1], match[0]);
}

export {
  useSandbox ,
  
}
/* react Not a pure module */
