// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Browser from "./Browser.mjs";

function text(prim) {
  return prim;
}

function update(model, msg) {
  if (msg) {
    return {
            value: model.value - 1 | 0
          };
  } else {
    return {
            value: model.value + 1 | 0
          };
  }
}

function button(action, textValue) {
  return React.createElement("button", {
              onClick: action
            }, textValue);
}

function view(dispatch, model, _props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Actual value: " + String(model.value)), button((function (param) {
                    return Curry._1(dispatch, /* Add */0);
                  }), "Add"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Remove */1);
                    })
                }, "Remove"));
}

var T_initialModel = {
  value: 0
};

var T = {
  initialModel: T_initialModel,
  update: update,
  view: view
};

function make(props) {
  return Curry._1(Browser.useSandbox(T), props);
}

export {
  text ,
  T ,
  make ,
  
}
/* react Not a pure module */
